### ISSUE TITLE
Get no prices anymore since today: state class measurement, device class monetary or timestamp

### ISSUE THREAD

**Issue by RobMeerwijk** [JaccoR/hass-entso-e#149]
From the log:
`Entity sensor.entso_e_highest_energy_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
Entity sensor.entso_e_average_electricity_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
Entity sensor.entso_e_current_percentage_of_highest_electricity_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('monetary') it is using; expected None or one of 'total'; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
Entity sensor.entso_e_time_of_highest_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('timestamp') it is using; expected None; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues
Entity sensor.entso_e_time_of_lowest_price_today (<class 'custom_components.entsoe.sensor.EntsoeSensor'>) is using state class 'measurement' which is impossible considering device class ('timestamp') it is using; expected None; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/JaccoR/hass-entso-e/issues`

**Comment by mstegen** [comment]
I don't think there is an issue with the integration. There doesn't seem to be any data for 5-4-24 for the Netherlands at the moment.
https://transparency.entsoe.eu/transmission-domain/r2/dayAheadPrices/show?name=&defaultValue=true&viewType=GRAPH&areaType=BZN&atch=false&dateTime.dateTime=05.04.2024+00:00|CET|DAY&biddingZone.values=CTY|10YNL----------L!BZN|10YNL----------L&resolution.values=PT15M&resolution.values=PT30M&resolution.values=PT60M&dateTime.timezone=CET_CEST&dateTime.timezone_input=CET+(UTC+1)+/+CEST+(UTC+2)

**Comment by RobMeerwijk** [comment]
Ok, thank you! That is weird. Energy Zero is providing day ahead prices for 5th of april.

**Comment by uermend** [comment]
issue is fixed. data again avalible from etsoe. so this was an Etsoe issue and not an issue with the integration.

**Comment by uermend** [comment]
HI,

yes I'have all the information and graphs work.
running 2024.4.2

**Comment by uermend** [comment]
![Prijzen Etsoe](https://github.com/JaccoR/hass-entso-e/assets/15028902/02f4ae89-9c60-47d9-8437-49ed45f0d343)

**Comment by RobMeerwijk** [comment]
> It might be fixed at Entsoe, but my HASS hasn't seen any new data since the 4th of April.
> 
> I've made sure my Entsoe account works (had to chang password to log in) I've regenerated the API key and added it to the Entose integration. I've restarted my HASS VM.
> 
> But still the latest data I see (Settings > Entities > Average Electricity price today > Attributes > prices today) is from 4 April 2024. And I see the same class mismatch errors as pasted above by @RobMeerwijk
> 
> @uermend Do your see up-to-date data again under Attributes and do your graphs work again? Did you need to do anything else? Wait a day for instance?

Same here, it is indeed not fixed. I still have the same error. I created a fall back with the energy zero integration, so I did not notice. Indeed no prices from this integration.
